[[constraint]]
  name = "github.com/cjbassi/drawille-go"
  branch = "master"

[[constraint]]
  name = "github.com/gdamore/tcell"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
